### ISSUE TITLE
Try to use fabric_cat_tools

### ISSUE THREAD

**Issue by Devis1996** [m-kovalsky/fabric_cat_tools#1] opened 2024-04-09 07:48 UTC
Hello!
First of All, thank you for fantastic tools.
I try to use fabric_cat_tools method run_model_bpa, but i find this error:
KeyError: "None of [Index(['Hierarchy Name'], dtype='object')] are in the [columns]"

I don't understand why thi heppened.
Versions:
Runtime 1.2
Spark 3.4
Delta 2.4

I attach the screen of code.
![2024-04-09_09h47_03](https://github.com/m-kovalsky/fabric_cat_tools/assets/48127472/c7037385-13a3-4d16-be3d-04e39303192e)
![2024-04-09_09h48_09](https://github.com/m-kovalsky/fabric_cat_tools/assets/48127472/1e33d41f-b6b7-4e35-862f-beed03007feb)

Thank you!

**Comment by m-kovalsky** [comment] 2024-04-09 08:57
A bit more context would be helpful but let's start with this. Would you run the following code and show me the headers for the columns:

```python
import sempy
import sempy.fabric as fabric
fabric.list_hierarchies(dataset = 'Daily Sellout')
```

**Comment by Devis1996** [comment] 2024-04-09 09:29
I attach the result:
![2024-04-09_11h28_08](https://github.com/m-kovalsky/fabric_cat_tools/assets/48127472/6eca0ec9-0d32-4277-813a-fae186d58ed9)

**Comment by m-kovalsky** [comment] 2024-04-09 10:08
Please send the entire error message

**Comment by Devis1996** [comment] 2024-04-09 10:13
I attach entire error message
[error.txt](https://github.com/m-kovalsky/fabric_cat_tools/files/14917198/error.txt)

**Comment by m-kovalsky** [comment] 2024-04-09 11:46
I'm not able to reproduce this error. Are you able to share your .bim file (over email)?

**Comment by Devis1996** [comment] 2024-04-09 12:04
The customer doesn't allow me to send the .bim, sorry

**Comment by Devis1996** [comment] 2024-04-10 12:50
I simplified the Model but I got the same error. Please leave me the email address so I can send you the .bim?
Thanks for the support

**Comment by m-kovalsky** [comment] 2024-04-10 13:22
***@***.***
________________________________

**Comment by Devis1996** [comment] 2024-04-10 13:36
Thank you!
________________________________
Da: m-kovalsky ***@***.***>
Inviato: mercoledì 10 aprile 2024 15:22
A: m-kovalsky/fabric_cat_tools ***@***.***>
Cc: Devis1996 ***@***.***>; Author ***@***.***>
Oggetto: Re: [m-kovalsky/fabric_cat_tools] Try to use fabric_cat_tools (Issue #1)


***@***.***
________________________________

**Comment by m-kovalsky** [comment] 2024-04-11 09:59
Please check but I believe this should be resolved in 0.2.5

**Comment by Devis1996** [comment] 2024-04-11 10:29
Thanks, now a result is displayed.
There is a problem reporting errors in calculation items. It is reported that the expression is missing, which is not true:
![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/48127472/f8fb1ffa-d7b4-4ab3-bdfa-0296c5a9152d)

**Comment by m-kovalsky** [comment] 2024-04-11 10:37
Ah, you are correct. Stop and restart the session and try running 0.2.5 again.

**Comment by Devis1996** [comment] 2024-04-11 10:41
Now everything is ok, thanks for the support!

Devis

**Closed as completed** 2024-04-11 10:51 UTC
Labels: bug
